language: cpp

sudo: required

dist: trusty

compiler:
  - g++

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y install build-essential cmake g++ git libboost-all-dev libbz2-dev libctemplate-dev libgflags-dev libgoogle-glog-dev libhwloc-dev libjansson-dev libprotobuf-dev libssl-dev make protobuf-compiler; fi

before_script: mkdir -p build && cd build && cmake .. -DCMAKE_CXX_COMPILER=$COMPILER

script: make

branches:
  only:
    - master

notifications:
  email: true
    - firmament-dev@camsas.org

os:
  - linux

cache:
  directories:
    - build/firmament
    - build/third_party
