language: go

dist: trusty

go:
  - 1.7.1

before_install:
  - go get github.com/mattn/goveralls

install:
  - # Do nothing. This is needed to prevent default instal action "go get -t -v ./..." from happening here.

script:
  - go build -v
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore="*.pb.go,*/*.pb.go,*/*/*.pb.go,*/*/*/*.pb.go,pkg/test/*,pkg/firmament_mock/*,pkg/*/*_test.go"

branches:
  only:
    - master

notifications:
  email: true
    - firmament-dev@camsas.org

os:
  - linux
