apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: poseidon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poseidon
subjects:
- kind: ServiceAccount
  name: poseidon
  namespace: poseidon-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: poseidon
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - poseidon
  resources:
  - endpoints
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - pods/binding
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poseidon
  namespace: poseidon-test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    component: poseidon
    tier: control-plane
    poseidonservice: poseidon
  name: poseidon
  namespace: poseidon-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: poseidon
        tier: control-plane
        version: first
        poseidonservice: poseidon
    spec:
      serviceAccountName: poseidon
      containers:
      - command: [/poseidon, --logtostderr, --kubeConfig=, --kubeVersion=1.6, --firmamentAddress=firmament-service.poseidon-test, --firmamentPort=9090]
        image: gcr.io/poseidon-173606/poseidon:latest
        name: poseidon
      initContainers:
      - name: init-firmamentservice
        image: radial/busyboxplus:curl
        command: ['sh', '-c', 'until nslookup firmament-service.poseidon-test; do echo waiting for firmamentservice; sleep 1; done;']
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
---
kind: Service
apiVersion: v1
metadata:
  name: poseidon
  namespace: poseidon-test
spec:
  selector:
    poseidonservice: poseidon
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
---
